ccflags-y += ${PROJECTINCLUDE} \
		-I$(ZEPHYR_BASE)/include/drivers \
		-I$(ZEPHYR_BASE)/nvisionit/common \
		-I$(ZEPHYR_BASE)/drivers \
		-I./include/

obj-y = main.o bmi160.o max30100.o max30100_beat_detector.o max30100_spo2_calculator.o max30100_pulse_oximeter.o
